Create mishba-ai.mdx
pbclife/gitopener.vercel.app pull request #107
Opened 2023-03-20 17:16 UTC by mishba-ai

## Fixes Issue

Closes #<issue_number>

## Changes proposed

## Screenshots

## Note to reviewers

2023-03-20 17:42 UTC, priyankarpal requested changes
You can see the example profile here. https://github.com/pbclife/gitopener.vercel.app/blob/main/contribution/priyankarpal.mdx?plain=1

- You can add your skills
- projects
- etc

2023-03-20 17:42 UTC, priyankarpal commented on contribution/mishba-ai.mdx
> +    icon={/* svg icon for Html */}
add svg icon

2023-03-22 03:09 UTC, mishba-ai commented on contribution/mishba-ai.mdx
> +    icon={/* svg icon for Html */}
done

2023-03-22 04:32 UTC, priyankarpal requested changes

2023-03-22 04:32 UTC, priyankarpal commented on contribution/mishba-ai.mdx
> +   Html
Everything looks good. But could you add your experience such as `1-year experience with HTML` 

``` suggestion
1-year experience with HTML
```

2023-03-22 04:32 UTC, priyankarpal commented on contribution/mishba-ai.mdx
> +    CSS
same here also

2023-03-22 13:07 UTC, priyankarpal requested changes

2023-03-22 13:07 UTC, priyankarpal commented on contribution/mishba-ai.mdx
> +level="Intermediate"
Remove this from here.

```suggestion

```

2023-03-22 13:07 UTC, priyankarpal commented on contribution/mishba-ai.mdx
> +    name="html"
add this here. after `name`

``` add
level="Intermediate"
```

2023-03-22 13:07 UTC, priyankarpal commented on contribution/mishba-ai.mdx
> +level="Intermediate"
Also remove from here.
```suggestion

```

2023-03-22 13:07 UTC, priyankarpal commented on contribution/mishba-ai.mdx
> +    name="CSS"
Add after `name`

```add
    level="Intermediate"
```

2023-03-22 13:19 UTC, priyankarpal submitted a review, later dismissed
Looks Good 🎉 You can customise your profile later.

2023-03-30 03:32 UTC, sboy99 approved these changes
LGTM 👌

2023-03-30 03:45 UTC, merged