Created srivatsavsurya.mdx
pbclife/gitopener.vercel.app pull request #128
Opened 2023-03-23 18:32 UTC by srivatsavsurya

2023-03-24 01:45 UTC, sboy99 requested changes
Add some content too, Your can view other contributors profile for reference

2023-03-24 02:28 UTC, priyankarpal commented
@srivatsavsurya  add your details such as skills, name, socials links etc.

2023-03-24 21:00 UTC, srivatsavsurya commented
Check now

2023-03-25 04:30 UTC, priyankarpal requested changes
Just small changes

2023-03-25 04:30 UTC, priyankarpal commented on contribution/srivatsavsurya.mdx
> +Hi👋 there! It's srivatsav, a Third-year MEchatronics Science Engineering student & a Tech + Mechanics Enthusiast. I'm a Student Engineer.I am always looking for ways to contribute to the open-source
``` suggestion
Hi👋 there! It's Srivastava, a Third-year Mechatronics Science Engineering student & a Tech + Mechanics Enthusiast. I'm a Student Engineer. I am always looking for ways to contribute to the open-source community and positively impact the tech industry.
```

2023-04-05 17:42 UTC, sboy99 approved these changes
LGTM

2023-04-05 17:44 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-04-05 17:44 UTC, merged