Create SajjanYadav.mdx
pbclife/gitopener.vercel.app pull request #131
Opened 2023-03-24 06:54 UTC by SajjanYadav

2023-03-24 07:08 UTC, priyankarpal requested changes

2023-03-24 07:08 UTC, priyankarpal commented on contribution/SajjanYadav.mdx
> +    >
Add this two lines after `>`

``` suggestion
    >
       </Skill>
  </Skills>
```

2023-03-24 07:14 UTC, priyankarpal approved these changes
Looks Good 🎉

2023-03-24 10:59 UTC, sboy99 requested changes

2023-03-24 10:59 UTC, sboy99 commented on contribution/SajjanYadav.mdx
> +        Javascript : <svg xmlns="http://www.w3.org/2000/svg" aria-label="JavaScript" viewBox="0 0 512 512" id="javascript"><rect width="512" height="512" fill="#f7df1e" rx="15%"></rect><path d="m324,
Pass only svg

2023-03-24 10:59 UTC, sboy99 commented on contribution/SajjanYadav.mdx
> +        Javascript : <svg xmlns="http://www.w3.org/2000/svg" aria-label="JavaScript" viewBox="0 0 512 512" id="javascript"><rect width="512" height="512" fill="#f7df1e" rx="15%"></rect><path d="m324,
remove the Javascript: one

2023-03-24 13:23 UTC, Deva-1903 approved these changes

2023-03-25 02:09 UTC, sboy99 approved these changes
LGTM 🐎

2023-03-25 02:14 UTC, merged