feat(templates): added issue and pr templates
pbclife/gitopener.vercel.app pull request #37
Opened 2023-01-20 20:52 UTC by Aadarsh805

2023-01-21 19:56 UTC, Aadarsh805 commented
@sboy99 have a look at the templates when you are free

2023-01-22 18:33 UTC, sboy99 commented
Can you provide some references of output, screenshot of a project using this template will be appreciated

2023-01-22 19:21 UTC, Aadarsh805 commented
> Can you provide some references of output, screenshot of a project using this template will be appreciated

yes sigmaTweet, https://github.com/Aadarsh805/SigmaTweet

2023-01-23 08:59 UTC, sboy99 requested changes
Some of the labels need to be renamed, I have mentioned that. If possible  add a documentation issue template which adds `documentation` label by default

2023-01-23 08:59 UTC, sboy99 commented on .github/ISSUE_TEMPLATE/bug.yml
> +labels: ["Goal: fix"]
Add label "bug / report " as the default, we don't have "Goal: fix" label

2023-01-23 08:59 UTC, sboy99 commented on .github/ISSUE_TEMPLATE/bug.yml
> +title: "[BUG] <Title>"
Change [BUG] <Title> to  Bug: <Title>

2023-01-23 08:59 UTC, sboy99 commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +title: "[Feature] <description>"
Change [Feature] <description>  to Feat: <Title>

2023-01-23 08:59 UTC, sboy99 commented on .github/ISSUE_TEMPLATE/feature_request.yml
> +labels: ["goal: addition"]
change "goal: addition" to "feat / request"

2023-01-23 08:59 UTC, sboy99 commented on .github/ISSUE_TEMPLATE/other.yml
> +labels: ["status: awaiting triage"]
remove `lebels`  for other request

2023-01-23 08:59 UTC, sboy99 commented on .github/pull_request_template.md
> +
add `closes #<issue_number>`

2023-01-23 18:15 UTC, merged