feat(refactor): renamed file names and fixed imports accordingly and …
pbclife/gitopener.vercel.app pull request #42
Opened 2023-01-21 20:26 UTC by Aadarsh805

…changed some components to FC

2023-01-21 20:27 UTC, Aadarsh805 commented
#36

2023-01-22 03:42 UTC, sboy99 requested changes
Make sure updating below mentioned changes for every modifications

2023-01-22 03:42 UTC, sboy99 commented on src/components/contributorpage/ContributorComp.tsx
> +import GithubIcon from '../icons/Github';
use absolute imports, for making the code base consistent use `@icons` and `@utilities`  instead of relative imports

2023-01-22 03:42 UTC, sboy99 commented on src/components/contributorpage/NewContributrs.tsx
>  import { FC } from 'react';
where importing types use type 
e.g: import type { FC } from 'react';

2023-01-23 11:54 UTC, closed without merging