Prev/next button
pbclife/gitopener.vercel.app pull request #71
Opened 2023-02-11 11:47 UTC by Aadarsh805

## Fixes Issue
closes #68

## Changes proposed
Added previous and next buttons to the bottom of docs pages for navigating between the docs

## Screenshots

![image](https://user-images.githubusercontent.com/95094057/218256336-2b636718-505b-458a-8450-c1fee3b57d3b.png)

2023-02-11 12:45 UTC, Aadarsh805 commented
@sboy99 I made icon files for prev and next icon, but they are not showing for some reason, do check that issue
I'm not sure if I'm using the correct icons

2023-02-11 16:23 UTC, sboy99 commented
Fixed the issue of svgs

2023-02-11 16:27 UTC, sboy99 requested changes
Super logic. really awesome, only few changes. Then we are good to 🚀

2023-02-11 16:27 UTC, sboy99 commented on src/components/icons/NextIcon.tsx
> +import { ComponentProps } from 'react';
no need to keep it. remove it

2023-02-11 16:27 UTC, sboy99 commented on src/components/icons/PrevIcon.tsx
> +import { ComponentProps } from 'react';
not in use, so we should remove it

2023-02-12 04:13 UTC, sboy99 approved these changes
Great Work 🎉 . LGTM

2023-02-12 04:15 UTC, merged